"""add face embeddings and person photo

Revision ID: 0cac19a54293
Revises: f49512503a51
Create Date: 2026-04-15 23:04:59.005624
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector


revision: str = '0cac19a54293'
down_revision: Union[str, None] = 'f49512503a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_embeddings_person_id'), 'face_embeddings', ['person_id'], unique=False)
    op.add_column('persons', sa.Column('photo_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'photo_path')
    op.drop_index(op.f('ix_face_embeddings_person_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    # ### end Alembic commands ###
