logLevel: info
logDestinations:
  - stdout

api: yes
apiAddress: ":9997"

authInternalUsers:
  - user: any
    pass: ""
    permissions:
      - action: publish
        path: ""
      - action: read
        path: ""
      - action: playback
        path: ""
      - action: api

rtsp: yes
rtspAddress: ":8554"
rtspTransports: [ tcp, udp ]

webrtc: yes
webrtcAddress: ":8889"

hls: yes
hlsAddress: ":8888"

paths:
  all_others:
    source: publisher
